[0m09:45:32.996944 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED2DF37A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED2F3EFC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED2F3EF890>]}


============================== 09:45:33.004308 | ad7aceea-07ff-4fc2-b99c-fd293776da0d ==============================
[0m09:45:33.004308 [info ] [MainThread]: Running with dbt=1.10.3
[0m09:45:33.005302 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\robbf\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt init dbt_project', 'send_anonymous_usage_stats': 'True'}
[0m09:45:33.048292 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\robbf\.dbt
[0m09:45:33.051327 [debug] [MainThread]: Starter project path: C:\Users\robbf\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\include\starter_project
[0m09:45:33.083528 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:45:33.084520 [info ] [MainThread]: Setting up your profile.
[0m09:51:49.270180 [info ] [MainThread]: Profile dbt_project written to C:\Users\robbf\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m09:51:49.273545 [debug] [MainThread]: Command `dbt init` succeeded at 09:51:49.273240 after 376.50 seconds
[0m09:51:49.274207 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED4CBD0050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED4CB5E690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED4CB1EAD0>]}
[0m09:51:49.275068 [debug] [MainThread]: Flushing usage events
[0m09:51:49.656124 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:01:15.932643 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6D6D47A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6D8207ED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6D8207B10>]}


============================== 10:01:15.938062 | da2e1fc7-b5b4-494f-a47e-d4459e49d8c5 ==============================
[0m10:01:15.938062 [info ] [MainThread]: Running with dbt=1.10.3
[0m10:01:15.939022 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\robbf\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:01:15.939605 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\robbf\Documents\ai-driven-gcp-data-warehouse\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:01:15.941124 [debug] [MainThread]: Command `dbt run` failed at 10:01:15.940954 after 0.24 seconds
[0m10:01:15.941567 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6D8235480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6D8111B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6D80AAE00>]}
[0m10:01:15.942009 [debug] [MainThread]: Flushing usage events
[0m10:01:16.341879 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:29:27.786823 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F802667A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F80390BED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F80390BB10>]}


============================== 09:29:27.795999 | eef799d2-6126-49e6-990d-714151b6ed00 ==============================
[0m09:29:27.795999 [info ] [MainThread]: Running with dbt=1.10.3
[0m09:29:27.797106 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\robbf\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m09:29:27.797802 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\robbf\Documents\ai-driven-gcp-data-warehouse\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:29:27.798847 [debug] [MainThread]: Command `dbt deps` failed at 09:29:27.798722 after 0.19 seconds
[0m09:29:27.799245 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F803939480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F803821B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8037BAF10>]}
[0m09:29:27.799654 [debug] [MainThread]: Flushing usage events
[0m09:29:28.224946 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:43:55.645575 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186DF427A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186E06DBED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186E06DBB10>]}


============================== 11:43:55.650766 | f7d8d206-98cb-4e0b-a977-d2d353217773 ==============================
[0m11:43:55.650766 [info ] [MainThread]: Running with dbt=1.10.3
[0m11:43:55.651808 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\robbf\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:43:55.652355 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\robbf\Documents\ai-driven-gcp-data-warehouse\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:43:55.653607 [debug] [MainThread]: Command `dbt run` failed at 11:43:55.653478 after 0.15 seconds
[0m11:43:55.654007 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186E0705480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186E05DDB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186E057AE00>]}
[0m11:43:55.654429 [debug] [MainThread]: Flushing usage events
[0m11:43:56.007554 [debug] [MainThread]: An error was encountered while trying to flush usage events
